name: talk_pad
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi: ^0.1.1+3
  speech_recognition: "^0.3.0"
  cupertino_icons: ^0.1.2
  button3d: "0.1.0"
  shimmer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/b.sf2
